#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PhxGauging.Resource", IsApplication=true)]

namespace PhxGauging
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PhxGauging.Common.Android.Resource.String.ApplicationName = global::PhxGauging.Resource.String.ApplicationName;
			global::PhxGauging.Common.Android.Resource.String.Hello = global::PhxGauging.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int Icon = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int pheonix_logo = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int splash = 2130771970;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020001
			public const int btnRefresh = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int itemText = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int itemTitle = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int myListItem = 2130837508;
			
			// aapt resource value: 0x7F020000
			public const int PhxlistView = 2130837504;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Disgover = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Gauging = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int Phx21 = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int WorkOrder = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7F040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7F040001
			public const int Hello = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
